CREATE TABLE public.alunos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf TEXT NOT NULL UNIQUE CHECK (cpf ~ CAST('^[0-9]{11}$' AS TEXT)),
  nascimento DATE NOT NULL,
  contato TEXT CHECK (contato ~ CAST('^[0-9]{10,11}$' AS TEXT)),
  contato_emergencia TEXT CHECK (
    contato_emergencia ~ CAST('^[0-9]{10,11}$' AS TEXT)
  ),
  email TEXT NOT NULL CHECK (
    email ~ CAST('^[\w\-\.]+@([\w-]+\.)+[\w-]{2,}$' AS TEXT)
  ),
  faixa public.faixa NOT NULL,
  grau SMALLINT NOT NULL CHECK (
    grau >= 0
    AND grau < 5
  ),
  tipo_sanguineo public.tipo_sanguineo NOT NULL,
  data_entrada DATE NOT NULL DEFAULT CURRENT_DATE,
  link_foto TEXT,
  id_responsavel INT REFERENCES public.responsaveis (id) 
    ON DELETE SET NULL 
    ON UPDATE CASCADE,
  id_turma INT REFERENCES public.turmas (id) 
    ON DELETE SET NULL 
    ON UPDATE CASCADE,
  federado BOOLEAN NOT NULL DEFAULT TRUE,
  id_ficha INT UNIQUE,
  apelido TEXT,
  usar_apelido BOOLEAN NOT NULL DEFAULT FALSE,
  p_medica1 BOOLEAN NOT NULL DEFAULT FALSE,
  p_medica2 BOOLEAN NOT NULL DEFAULT FALSE,
  p_medica3 BOOLEAN NOT NULL DEFAULT FALSE,
  p_medica4 BOOLEAN NOT NULL DEFAULT FALSE,
  p_medica5 BOOLEAN NOT NULL DEFAULT FALSE,
  observacao_medica TEXT,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE public.alunos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Give full access to all authenticated users"
ON public.alunos
AS PERMISSIVE
FOR ALL
TO authenticated
USING (TRUE)
WITH CHECK (TRUE);