-- 1. Tabela de Doações
CREATE TABLE IF NOT EXISTS public.doacoes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador TEXT NOT NULL,
    cor public.cor_kimono NOT NULL,
    tamanho public.tamanho_kimono NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade > 0),
    data DATE NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE public.doacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Give full access to all authenticated users"
ON public.doacoes
AS PERMISSIVE
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 2. Tabela de Empréstimos
CREATE TABLE IF NOT EXISTS public.emprestimos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id INT REFERENCES public.alunos(id) NOT NULL,
    cor public.cor_kimono NOT NULL,
    tamanho public.tamanho_kimono NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    data_devolucao DATE
);

ALTER TABLE public.emprestimos ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX uk_apenas_um_emprestimo_ativo
ON public.emprestimos (aluno_id)
WHERE data_devolucao IS NULL;

CREATE POLICY "Give full access to all authenticated users"
ON public.emprestimos
AS PERMISSIVE
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 3. Tabela de Perdas
CREATE TABLE IF NOT EXISTS public.perdas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cor public.cor_kimono NOT NULL,
    tamanho public.tamanho_kimono NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade > 0),
    motivo TEXT NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE public.perdas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Give full access to all authenticated users"
ON public.perdas
AS PERMISSIVE
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);