CREATE TABLE IF NOT EXISTS public.observacoes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  voluntario UUID NOT NULL REFERENCES public.users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  observacao TEXT NOT NULL,
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  turma_id INT NOT NULL references public.turmas(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT observacoes_turma_data_key UNIQUE (turma_id, data)
);

ALTER TABLE public.observacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Give full access to all authenticated users"
ON public.observacoes
AS PERMISSIVE
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);