CREATE TABLE IF NOT EXISTS public.presencas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  aluno_id INT NOT NULL REFERENCES public.alunos(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  turma_id INT NOT NULL REFERENCES public.turmas(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT presencas_aluno_turma_data_key UNIQUE (aluno_id, turma_id, data)
);

ALTER TABLE public.presencas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Give full access to all authenticated users"
ON public.presencas
AS PERMISSIVE
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);