CREATE TABLE IF NOT EXISTS public.responsaveis (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf TEXT NOT NULL UNIQUE
    CONSTRAINT cpf_valido
    CHECK (cpf ~ '^[0-9]{11}$'),
  contato TEXT NOT NULL
    CONSTRAINT contato_valido
    CHECK (contato ~ '^[0-9]{10,11}$'),
  email TEXT NOT NULL
    CONSTRAINT email_valido 
    CHECK (email ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]{2,}$'),
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE public.responsaveis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Give full access to all authenticated users"
ON public.responsaveis
AS PERMISSIVE
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);